# Generated by Django 6.1.1 on 2026-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(default='Visakhapatnam', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('zone', models.CharField(default='Central Zone', max_length=100)),
                ('city', models.CharField(default='Visakhapatnam', max_length=100)),
                ('population', models.PositiveIntegerField(default=50000)),
                ('population_density', models.PositiveIntegerField(default=5000, help_text='People per sq km')),
                ('vulnerability_score', models.FloatField(default=50.0, help_text='0-100 demographic vulnerability score')),
                ('outdoor_worker_ratio', models.FloatField(default=0.3, help_text='Fraction of population working outdoors')),
                ('healthcare_access_score', models.FloatField(default=60.0, help_text='0-100 rating')),
                ('green_cover_percent', models.FloatField(default=20.0, help_text='Percentage green canopy cover')),
                ('primary_exposure', models.TextField(blank=True, default='')),
                ('geometry_geojson', models.JSONField(help_text='GeoJSON polygon or multipolygon geometry')),
                ('centroid_lat', models.FloatField()),
                ('centroid_lon', models.FloatField()),
                ('current_htsi', models.FloatField(default=45.0)),
                ('current_risk', models.CharField(default='HIGH', max_length=20)),
                ('last_risk_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
