# Generated by Django 6.0.7 on 2026-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='ward',
            name='city',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
