# Generated by Django 6.1.1 on 2026-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('EXTREME_HEAT', 'Extreme Heat Emergency'), ('VERY_HIGH_HEAT', 'Very High Heat Warning'), ('HIGH_HEAT', 'High Heat Advisory'), ('ESCALATION', 'Rapid Risk Escalation Alert'), ('ACTION_RECOMMENDATION', 'Protective Action Protocol')], default='HIGH_HEAT', max_length=40)),
                ('risk_level', models.CharField(default='HIGH', max_length=20)),
                ('htsi', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recommended_actions', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
