# Generated by Django 6.1.1 on 2026-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(help_text='Dry-bulb temperature in °C')),
                ('humidity', models.FloatField(help_text='Relative humidity in %')),
                ('wind_speed', models.FloatField(default=1.0, help_text='Wind speed in m/s')),
                ('solar_radiation', models.FloatField(default=0.0, help_text='Surface solar radiation in W/m²')),
                ('heat_index', models.FloatField()),
                ('wbgt', models.FloatField()),
                ('utci', models.FloatField()),
                ('htsi', models.FloatField(db_index=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY HIGH', 'Very High'), ('EXTREME', 'Extreme')], db_index=True, max_length=20)),
                ('vulnerability_score', models.FloatField(default=50.0)),
                ('is_forecast', models.BooleanField(default=False)),
                ('source', models.CharField(default='Open-Meteo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ward_name', 'timestamp'], name='thermal_the_ward_na_f3a236_idx'), models.Index(fields=['risk_level', 'htsi'], name='thermal_the_risk_le_bcbe9f_idx')],
            },
        ),
    ]
