# Generated by Django 6.1.1 on 2026-09-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_htsi', models.FloatField(default=40.0, help_text='Trigger threshold minimum HTSI')),
                ('max_htsi', models.FloatField(default=100.0)),
                ('priority_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=20)),
                ('target_category', models.CharField(choices=[('COOLING', 'Cooling Shelters & Mist Stations'), ('HEALTH', 'Hospital & Ambulance Surge'), ('LABOUR', 'Outdoor Work Restrictions'), ('WATER', 'Drinking Water Deployment'), ('POWER', 'Grid Readiness & Cool Roofs'), ('ADVISORY', 'Public Warnings & Media')], default='COOLING', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-min_htsi', 'priority_level'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('htsi', models.FloatField()),
                ('population', models.PositiveIntegerField()),
                ('population_density', models.PositiveIntegerField()),
                ('vulnerability_score', models.FloatField()),
                ('priority_score', models.FloatField(help_text='Computed Emergency Urgency Score')),
                ('priority_rank', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('recommended_actions', models.JSONField(default=list)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_priorities', to='gis.ward')),
            ],
            options={
                'ordering': ['priority_rank', '-priority_score'],
            },
        ),
    ]
