# Generated by Django 6.1.1 on 2026-09-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Visakhapatnam', max_length=100)),
                ('forecast_time', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('solar_radiation', models.FloatField(default=0.0)),
                ('apparent_temperature', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='Open-Meteo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_forecasts', to='gis.ward')),
            ],
            options={
                'ordering': ['forecast_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Visakhapatnam', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('humidity', models.FloatField(help_text='Relative humidity in %')),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s')),
                ('solar_radiation', models.FloatField(default=0.0, help_text='Direct/Global solar radiation W/m²')),
                ('pressure', models.FloatField(blank=True, help_text='Surface pressure in hPa', null=True)),
                ('cloud_cover', models.FloatField(blank=True, help_text='Cloud cover percentage', null=True)),
                ('apparent_temperature', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='Open-Meteo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_observations', to='gis.ward')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ward', 'timestamp'], name='weather_wea_ward_id_78d0b2_idx')],
            },
        ),
    ]
