# Generated by Django 6.1.1 on 2026-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Custom Heat Scenario', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_temperature', models.FloatField()),
                ('input_humidity', models.FloatField()),
                ('input_wind_speed', models.FloatField(default=1.5)),
                ('input_solar_radiation', models.FloatField(default=600.0)),
                ('input_vulnerability', models.FloatField(default=50.0)),
                ('calculated_heat_index', models.FloatField()),
                ('calculated_wbgt', models.FloatField()),
                ('calculated_utci', models.FloatField()),
                ('calculated_htsi', models.FloatField()),
                ('calculated_risk_level', models.CharField(max_length=30)),
                ('baseline_htsi', models.FloatField(default=0.0)),
                ('htsi_difference', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
